spring.application.name=zencom-shop

# ===== DATASOURCE =====
spring.datasource.url=jdbc:postgresql://localhost:5435/zencom
spring.datasource.username=zencom
spring.datasource.password=zencom

# ===== JPA / HIBERNATE =====
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

# ===== LOGGING =====
logging.level.org.hibernate.SQL=debug

security.jwt.secret=9d9f3b2a7e0d4c7b8b5d1a2f3c4e5f6a9d9f3b2a7e0d4c7b8b5d1a2f3c4e5f6a
security.jwt.expirationSeconds=3600

#====== RABBITMQ =======
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=zencom
spring.rabbitmq.password=zencom
spring.rabbitmq.virtual-host=/
spring.rabbitmq.dynamic=true
