spring.application.name=zencom-shop

# ===== DATASOURCE =====
spring.datasource.url=url
spring.datasource.username=user
spring.datasource.password=password

# ===== JPA / HIBERNATE =====
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

# ===== LOGGING =====
logging.level.org.hibernate.SQL=debug

security.jwt.secret=${JWT_SECRET}
security.jwt.expirationSeconds=${JWT_EXPIRATION_TIME}

#====== RABBITMQ =======
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=user
spring.rabbitmq.password=password
spring.rabbitmq.virtual-host=/
spring.rabbitmq.dynamic=true

spring.profiles.active=dev
